// Define arrays of meal options with recipes for different diets
const breakfastOptions = {
    standard: [
        { meal: "Oatmeal with fruits", recipe: "Cook 1 cup oats with 2 cups water. Add fruits like bananas and berries, and top with 1 tablespoon honey or maple syrup." },
        { meal: "Avocado toast", recipe: "Toast 2 slices of whole grain bread. Spread 1 mashed avocado on top, sprinkle with salt and pepper, and drizzle with olive oil." },
        { meal: "Greek yogurt with berries", recipe: "Mix 1 cup Greek yogurt with 1/2 cup fresh berries like strawberries, blueberries, and raspberries. Add 1 tablespoon honey." },
        { meal: "Smoothie bowl", recipe: "Blend 1 frozen banana, 1 cup frozen berries, and 1/2 cup yogurt or milk until smooth. Pour into a bowl and top with granola, nuts, and fruits." },
        { meal: "Eggs and toast", recipe: "Fry or scramble 2 eggs. Serve with 2 slices of toasted bread, optionally spread with butter or jam." },
        { meal: "Pancakes with syrup", recipe: "Mix 1 cup flour, 1 egg, 1 cup milk, and 1 teaspoon baking powder to make pancake batter. Cook pancakes on a griddle and serve with syrup." },
        { meal: "Banana smoothie", recipe: "Blend 1 banana, 1 cup milk, 1 tablespoon peanut butter, and 1 tablespoon honey until smooth." },
        { meal: "Breakfast burrito", recipe: "Scramble 2 eggs with 1/4 cup diced bell peppers and onions. Wrap in a tortilla with 1/4 cup shredded cheese and salsa." },
        { meal: "French toast", recipe: "Whisk 2 eggs with 1/2 cup milk and 1 teaspoon cinnamon. Dip 2 slices of bread in the mixture and cook on a griddle until golden brown." },
        { meal: "Veggie omelette", recipe: "Whisk 2 eggs and pour into a hot pan. Add 1/4 cup diced tomatoes, bell peppers, and spinach. Cook until eggs are set." },
        { meal: "Muesli with fruits", recipe: "Combine 1 cup rolled oats, 1/4 cup nuts, 1/4 cup dried fruits, and 1 cup yogurt. Serve with fresh fruits." },
        { meal: "Chia seed pudding", recipe: "Mix 3 tablespoons chia seeds with 1 cup almond milk and 1 tablespoon honey. Refrigerate overnight and top with fresh fruits." },
        { meal: "Bagel with cream cheese", recipe: "Toast a bagel and spread with 2 tablespoons cream cheese. Top with sliced cucumbers and tomatoes." },
        { meal: "Quinoa breakfast bowl", recipe: "Cook 1/2 cup quinoa with 1 cup water. Top with 1/4 cup nuts, 1/4 cup dried fruits, and 1 tablespoon honey." },
        { meal: "Granola parfait", recipe: "Layer 1 cup Greek yogurt with 1/2 cup granola and 1/2 cup fresh berries in a glass." },
        { meal: "Apple cinnamon oatmeal", recipe: "Cook 1 cup oats with 2 cups water and 1 diced apple. Add 1 teaspoon cinnamon and 1 tablespoon honey." },
        { meal: "Breakfast sandwich", recipe: "Fry 1 egg and place on an English muffin with 1 slice of cheese and 1 slice of ham or turkey." },
        { meal: "Tofu scramble", recipe: "Crumble 1/2 block of tofu and stir-fry with 1/4 cup diced bell peppers, onions, and spinach. Season with turmeric and salt." },
        { meal: "Egg muffins", recipe: "Whisk 6 eggs and pour into muffin tins. Add diced vegetables and cheese. Bake at 350°F for 20 minutes." },
        { meal: "Breakfast pizza", recipe: "Top a pizza crust with scrambled eggs, diced vegetables, and cheese. Bake at 400°F for 10 minutes." }
    ],
    diabetic: [
        { meal: "Oatmeal with berries", recipe: "Cook 1/2 cup oats with 1 cup water. Add 1/2 cup fresh berries and 1 tablespoon ground flaxseed." },
        { meal: "Greek yogurt with nuts", recipe: "Mix 1 cup Greek yogurt with 1/4 cup nuts like almonds or walnuts. Add a sprinkle of cinnamon." },
        { meal: "Vegetable omelette", recipe: "Whisk 2 eggs and pour into a hot pan. Add 1/4 cup diced tomatoes, bell peppers, and spinach. Cook until eggs are set." },
        { meal: "Smoothie with spinach", recipe: "Blend 1 cup spinach, 1/2 cup frozen berries, 1/2 banana, and 1 cup almond milk until smooth." },
        { meal: "Avocado and egg", recipe: "Slice 1 avocado in half and remove the pit. Fill with 1 boiled egg, diced, and sprinkle with salt and pepper." },
        { meal: "Whole grain toast with peanut butter", recipe: "Toast 1 slice of whole grain bread and spread with 2 tablespoons peanut butter. Top with sliced bananas or berries." },
        { meal: "Cottage cheese with fruit", recipe: "Mix 1 cup cottage cheese with 1/2 cup fresh berries or sliced peaches." },
        { meal: "Chia pudding with berries", recipe: "Mix 3 tablespoons chia seeds with 1 cup almond milk and 1/2 teaspoon vanilla extract. Refrigerate overnight and top with fresh berries." },
        { meal: "Breakfast burrito", recipe: "Scramble 2 eggs with 1/4 cup diced bell peppers and onions. Wrap in a whole grain tortilla with salsa." },
        { meal: "Quinoa breakfast bowl", recipe: "Cook 1/2 cup quinoa with 1 cup water. Top with 1/4 cup nuts, 1/4 cup dried fruits, and a drizzle of honey." },
        { meal: "Egg and vegetable muffin", recipe: "Whisk 6 eggs and pour into muffin tins. Add diced vegetables like spinach, tomatoes, and bell peppers. Bake at 350°F for 20 minutes." },
        { meal: "Cinnamon apple oats", recipe: "Cook 1/2 cup oats with 1 cup water and 1 diced apple. Add 1 teaspoon cinnamon." },
        { meal: "Smoothie bowl with nuts", recipe: "Blend 1/2 cup frozen berries, 1/2 banana, and 1 cup almond milk until smooth. Pour into a bowl and top with nuts and seeds." },
        { meal: "Veggie scramble", recipe: "Scramble 2 eggs with 1/4 cup diced bell peppers, onions, and spinach." },
        { meal: "Whole grain cereal with milk", recipe: "Serve 1 cup whole grain cereal with 1 cup milk and top with fresh berries." },
        { meal: "Berry parfait", recipe: "Layer 1 cup Greek yogurt with 1/2 cup fresh berries and 1/4 cup nuts." },
        { meal: "Turkey and avocado toast", recipe: "Toast 1 slice of whole grain bread. Top with 2 slices of turkey and 1/2 avocado, mashed." },
        { meal: "Protein smoothie", recipe: "Blend 1 scoop protein powder, 1/2 banana, 1 tablespoon peanut butter, and 1 cup almond milk until smooth." },
        { meal: "Vegetable frittata", recipe: "Whisk 4 eggs and pour into a hot pan. Add 1/2 cup diced vegetables like spinach, tomatoes, and bell peppers. Cook until eggs are set." },
        { meal: "Pumpkin oatmeal", recipe: "Cook 1/2 cup oats with 1 cup water and 1/4 cup canned pumpkin. Add 1 teaspoon pumpkin pie spice and a drizzle of honey." }
    ]
};

const lunchOptions = {
    standard: [
        { meal: "Grilled chicken salad", recipe: "Grill 1 chicken breast and slice. Serve over mixed greens with 1/2 cup cherry tomatoes, 1/4 cup cucumbers, and dressing." },
        { meal: "Quinoa and vegetable stir-fry", recipe: "Cook 1 cup quinoa. Stir-fry with 1 cup mixed vegetables like bell peppers, broccoli, and carrots." },
        { meal: "Turkey and cheese sandwich", recipe: "Layer 2 slices of turkey, 1 slice of cheese, 2 slices of lettuce, and 1 slice of tomato between 2 slices of bread. Add condiments." },
        { meal: "Vegetable soup", recipe: "Simmer 2 cups mixed vegetables like carrots, celery, and potatoes in 4 cups vegetable broth. Season with herbs." },
        { meal: "Pasta with marinara sauce", recipe: "Cook 2 cups pasta. Toss with 1 cup marinara sauce made from tomatoes, garlic, and basil." },
        { meal: "Chicken Caesar wrap", recipe: "Grill 1 chicken breast and slice. Wrap with 1 cup lettuce, 2 tablespoons Parmesan cheese, and 2 tablespoons Caesar dressing in a tortilla." },
        { meal: "Tuna salad", recipe: "Mix 1 can tuna with 2 tablespoons mayonnaise, 1/4 cup diced celery, and 1/4 cup diced onions. Serve on a bed of lettuce or in a sandwich." },
        { meal: "Veggie wrap", recipe: "Spread 2 tablespoons hummus on a tortilla. Add 1/2 cup sliced bell peppers, cucumbers, and carrots. Roll up." },
        { meal: "Chicken and rice", recipe: "Grill 1 chicken breast and slice. Serve with 1 cup cooked rice and 1/2 cup steamed broccoli." },
        { meal: "Egg salad sandwich", recipe: "Mix 2 boiled eggs, diced, with 2 tablespoons mayonnaise and 1/4 cup diced celery. Serve on whole grain bread." },
        { meal: "Grilled cheese sandwich", recipe: "Layer 2 slices of cheese between 2 slices of bread. Cook in a pan until cheese is melted and bread is golden brown." },
        { meal: "Lentil soup", recipe: "Simmer 1 cup lentils with 4 cups vegetable broth, 1 diced carrot, 1 diced celery stalk, and 1 diced onion. Season with herbs." },
        { meal: "Caprese salad", recipe: "Layer 1 cup sliced tomatoes, 1/2 cup sliced mozzarella cheese, and fresh basil leaves. Drizzle with olive oil and balsamic vinegar." },
        { meal: "Chicken noodle soup", recipe: "Simmer 1 cup cooked chicken, 2 cups chicken broth, 1 cup noodles, and 1/2 cup mixed vegetables until heated through." },
        { meal: "BLT sandwich", recipe: "Layer 2 slices of cooked bacon, 1 slice of lettuce, and 1 slice of tomato between 2 slices of bread. Add mayonnaise if desired." },
        { meal: "Falafel wrap", recipe: "Prepare falafel from chickpeas. Wrap in a tortilla with 1/2 cup sliced vegetables and 2 tablespoons tahini sauce." },
        { meal: "Sushi rolls", recipe: "Prepare sushi rolls with 1 sheet of seaweed, 1 cup sushi rice, and fillings like cucumber, avocado, and cooked fish." },
        { meal: "Chicken salad", recipe: "Mix 1 cup cooked, diced chicken with 1/4 cup diced celery, 1/4 cup diced apples, and 2 tablespoons mayonnaise. Serve on a bed of lettuce." },
        { meal: "Shrimp salad", recipe: "Mix 1 cup cooked shrimp with 1/4 cup diced celery, 1/4 cup diced bell peppers, and 2 tablespoons mayonnaise. Serve on a bed of lettuce." },
        { meal: "Ham and cheese sandwich", recipe: "Layer 2 slices of ham, 1 slice of cheese, 2 slices of lettuce, and 1 slice of tomato between 2 slices of bread. Add condiments." }
    ],
    diabetic: [
        { meal: "Grilled chicken and vegetable salad", recipe: "Grill 1 chicken breast and slice. Serve over mixed greens with 1/2 cup cherry tomatoes, 1/4 cup cucumbers, and 1/4 cup bell peppers. Add a light vinaigrette." },
        { meal: "Quinoa and black bean salad", recipe: "Cook 1 cup quinoa and mix with 1 cup black beans, 1/2 cup diced tomatoes, 1/4 cup diced bell peppers, and 1/4 cup corn. Add lime juice and cilantro." },
        { meal: "Turkey and avocado sandwich", recipe: "Layer 2 slices of turkey, 1/2 sliced avocado, 2 slices of lettuce, and 1 slice of tomato between 2 slices of whole grain bread." },
        { meal: "Vegetable soup with beans", recipe: "Simmer 2 cups mixed vegetables like carrots, celery, and zucchini with 4 cups vegetable broth and 1 cup beans. Season with herbs." },
        { meal: "Whole wheat pasta with marinara sauce", recipe: "Cook 2 cups whole wheat pasta. Toss with 1 cup marinara sauce made from tomatoes, garlic, and basil." },
        { meal: "Chicken and vegetable stir-fry", recipe: "Stir-fry 1 sliced chicken breast with 1 cup mixed vegetables like bell peppers, broccoli, and snap peas. Season with soy sauce." },
        { meal: "Tuna and white bean salad", recipe: "Mix 1 can tuna with 1 cup white beans, 1/4 cup diced tomatoes, 1/4 cup diced bell peppers, and 1/4 cup red onions. Drizzle with olive oil and vinegar." },
        { meal: "Veggie wrap with hummus", recipe: "Spread 2 tablespoons hummus on a whole grain tortilla. Add 1/2 cup sliced bell peppers, cucumbers, and carrots. Roll up." },
        { meal: "Chicken and quinoa", recipe: "Grill 1 chicken breast and slice. Serve with 1 cup cooked quinoa and 1/2 cup steamed broccoli." },
        { meal: "Egg salad on lettuce", recipe: "Mix 2 boiled eggs, diced, with 2 tablespoons mayonnaise and 1/4 cup diced celery. Serve on a bed of lettuce." },
        { meal: "Grilled cheese with tomato soup", recipe: "Layer 2 slices of cheese between 2 slices of whole grain bread. Cook in a pan until cheese is melted and bread is golden brown. Serve with a cup of tomato soup." },
        { meal: "Lentil and vegetable soup", recipe: "Simmer 1 cup lentils with 4 cups vegetable broth, 1 diced carrot, 1 diced celery stalk, and 1 diced onion. Season with herbs." },
        { meal: "Caprese salad with avocado", recipe: "Layer 1 cup sliced tomatoes, 1/2 cup sliced mozzarella cheese, fresh basil leaves, and 1/2 sliced avocado. Drizzle with olive oil and balsamic vinegar." },
        { meal: "Chicken and vegetable soup", recipe: "Simmer 1 cup cooked chicken, 2 cups chicken broth, 1 cup whole grain noodles, and 1/2 cup mixed vegetables until heated through." },
        { meal: "BLT with avocado", recipe: "Layer 2 slices of cooked bacon, 1 slice of lettuce, 1 slice of tomato, and 1/2 sliced avocado between 2 slices of whole grain bread. Add mayonnaise if desired." },
        { meal: "Falafel and vegetable wrap", recipe: "Prepare falafel from chickpeas. Wrap in a whole grain tortilla with 1/2 cup sliced vegetables and 2 tablespoons tahini sauce." },
        { meal: "Sushi rolls with brown rice", recipe: "Prepare sushi rolls with 1 sheet of seaweed, 1 cup brown sushi rice, and fillings like cucumber, avocado, and cooked fish." },
        { meal: "Chicken and apple salad", recipe: "Mix 1 cup cooked, diced chicken with 1/4 cup diced celery, 1/4 cup diced apples, and 2 tablespoons mayonnaise. Serve on a bed of lettuce." },
        { meal: "Shrimp and avocado salad", recipe: "Mix 1 cup cooked shrimp with 1/2 sliced avocado, 1/4 cup diced bell peppers, and 2 tablespoons olive oil. Serve on a bed of lettuce." },
        { meal: "Ham and vegetable sandwich", recipe: "Layer 2 slices of ham, 1/2 sliced avocado, 2 slices of lettuce, and 1 slice of tomato between 2 slices of whole grain bread. Add condiments." }
    ]
};

const dinnerOptions = {
    standard: [
        { meal: "Spaghetti and meatballs", recipe: "Cook 2 cups spaghetti. Prepare meatballs from 1 pound ground beef, 1/2 cup breadcrumbs, 1 egg, and seasonings. Combine with marinara sauce." },
        { meal: "Grilled steak with mashed potatoes", recipe: "Grill 1 steak to desired doneness. Serve with 1 cup mashed potatoes and 1/2 cup steamed vegetables." },
        { meal: "Chicken Alfredo", recipe: "Cook 2 cups fettuccine. Prepare Alfredo sauce from 1 cup cream, 1/2 cup butter, and 1 cup Parmesan cheese. Add grilled chicken." },
        { meal: "Fish and chips", recipe: "Fry 2 fish fillets. Serve with homemade potato fries and 1/4 cup tartar sauce." },
        { meal: "Vegetable stir-fry with rice", recipe: "Stir-fry 2 cups mixed vegetables with soy sauce. Serve over 2 cups steamed rice." },
        { meal: "Beef tacos", recipe: "Cook 1 pound ground beef with taco seasoning. Serve in tortillas with lettuce, cheese, and salsa." },
        { meal: "Chicken Parmesan", recipe: "Bread and fry 2 chicken breasts. Top with marinara sauce and mozzarella cheese. Serve with spaghetti." },
        { meal: "Baked salmon with quinoa", recipe: "Bake 2 salmon fillets. Serve with 1 cup cooked quinoa and 1/2 cup steamed broccoli." },
        { meal: "Stuffed bell peppers", recipe: "Stuff 2 bell peppers with a mixture of 1 cup ground beef, 1 cup rice, and 1/2 cup cheese. Bake until tender." },
        { meal: "Shrimp scampi", recipe: "Cook 1 pound shrimp with garlic and butter. Serve over 2 cups cooked linguine." },
        { meal: "Chicken stir-fry", recipe: "Stir-fry 1 sliced chicken breast with 2 cups mixed vegetables and soy sauce. Serve over 2 cups steamed rice." },
        { meal: "Vegetable lasagna", recipe: "Layer lasagna noodles with a mixture of 2 cups ricotta cheese, 1 cup spinach, and 1 cup marinara sauce. Top with mozzarella cheese and bake." },
        { meal: "Pork chops with applesauce", recipe: "Grill 2 pork chops. Serve with 1/2 cup applesauce and 1/2 cup steamed green beans." },
        { meal: "Beef stew", recipe: "Simmer 1 pound beef cubes with 2 cups beef broth, 1 cup diced potatoes, 1 cup diced carrots, and seasonings until tender." },
        { meal: "Chicken curry with rice", recipe: "Cook 1 sliced chicken breast with 1 cup curry sauce. Serve over 2 cups steamed rice." },
        { meal: "Vegetable soup with bread", recipe: "Simmer 2 cups mixed vegetables with 4 cups vegetable broth. Serve with crusty bread." },
        { meal: "Spaghetti carbonara", recipe: "Cook 2 cups spaghetti. Toss with a mixture of 1/2 cup cooked bacon, 2 eggs, and 1 cup Parmesan cheese." },
        { meal: "Beef stroganoff", recipe: "Cook 1 pound beef strips with 1 cup mushrooms and 1 cup sour cream. Serve over 2 cups egg noodles." },
        { meal: "Chicken enchiladas", recipe: "Roll 1 cup shredded chicken and 1/2 cup cheese in tortillas. Top with enchilada sauce and bake." },
        { meal: "Baked ziti", recipe: "Mix 2 cups cooked ziti with 1 cup ricotta cheese, 1 cup marinara sauce, and 1 cup mozzarella cheese. Bake until bubbly." }
    ],
    diabetic: [
        { meal: "Grilled chicken with roasted vegetables", recipe: "Grill 1 chicken breast. Serve with 1 cup roasted vegetables like broccoli, carrots, and bell peppers." },
        { meal: "Quinoa and black bean bowl", recipe: "Cook 1 cup quinoa and mix with 1 cup black beans, 1/2 cup diced tomatoes, 1/4 cup diced bell peppers, and 1/4 cup corn. Add lime juice and cilantro." },
        { meal: "Turkey and vegetable stir-fry", recipe: "Stir-fry 1 cup sliced turkey breast with 2 cups mixed vegetables like bell peppers, broccoli, and snap peas. Season with soy sauce." },
        { meal: "Vegetable soup with beans", recipe: "Simmer 2 cups mixed vegetables like carrots, celery, and zucchini with 4 cups vegetable broth and 1 cup beans. Season with herbs." },
        { meal: "Whole wheat pasta with marinara sauce", recipe: "Cook 2 cups whole wheat pasta. Toss with 1 cup marinara sauce made from tomatoes, garlic, and basil." },
        { meal: "Chicken and vegetable kebabs", recipe: "Skewer 1 sliced chicken breast with 2 cups mixed vegetables like bell peppers, onions, and zucchini. Grill until cooked." },
        { meal: "Salmon with quinoa and broccoli", recipe: "Bake 2 salmon fillets. Serve with 1 cup cooked quinoa and 1/2 cup steamed broccoli." },
        { meal: "Vegetable curry with brown rice", recipe: "Cook 1 cup mixed vegetables with 1 cup curry sauce. Serve over 2 cups steamed brown rice." },
        { meal: "Chicken and vegetable soup", recipe: "Simmer 1 cup cooked chicken, 2 cups chicken broth, 1 cup whole grain noodles, and 1/2 cup mixed vegetables until heated through." },
        { meal: "Stuffed bell peppers with quinoa", recipe: "Stuff 2 bell peppers with a mixture of 1 cup cooked quinoa, 1 cup black beans, and 1/2 cup diced tomatoes. Bake until tender." },
        { meal: "Shrimp and vegetable stir-fry", recipe: "Stir-fry 1 pound shrimp with 2 cups mixed vegetables and soy sauce. Serve over 2 cups steamed brown rice." },
        { meal: "Vegetable lasagna with whole wheat noodles", recipe: "Layer whole wheat lasagna noodles with a mixture of 2 cups ricotta cheese, 1 cup spinach, and 1 cup marinara sauce. Top with mozzarella cheese and bake." },
        { meal: "Chicken and broccoli stir-fry", recipe: "Stir-fry 1 sliced chicken breast with 2 cups broccoli florets and soy sauce. Serve over 2 cups steamed brown rice." },
        { meal: "Turkey chili", recipe: "Cook 1 pound ground turkey with 1 cup diced tomatoes, 1 cup kidney beans, and chili seasoning. Simmer until flavors blend." },
        { meal: "Salmon with asparagus", recipe: "Bake 2 salmon fillets. Serve with roasted asparagus and a squeeze of lemon." },
        { meal: "Vegetable quinoa pilaf", recipe: "Cook 1 cup quinoa and mix with 2 cups mixed vegetables like bell peppers, carrots, and peas. Season with herbs." },
        { meal: "Turkey meatballs with zucchini noodles", recipe: "Prepare turkey meatballs with lean ground turkey, oats, and spices. Serve over spiralized zucchini noodles with marinara sauce." },
        { meal: "Chicken and spinach salad", recipe: "Grill 1 chicken breast and slice. Serve over spinach with sliced strawberries, almonds, and a light vinaigrette." },
        { meal: "Beef and vegetable stir-fry", recipe: "Stir-fry 1 cup sliced beef with 2 cups mixed vegetables like bell peppers, onions, and snap peas. Season with soy sauce." },
        { meal: "Vegetarian stuffed peppers", recipe: "Stuff 2 bell peppers with a mixture of 1 cup quinoa, 1 cup black beans, diced tomatoes, and spices. Bake until peppers are tender." }
    ]
};
const snackOptions = {
    standard: [
        { snack: "Mixed nuts", description: "A handful of mixed nuts like almonds, walnuts, and cashews." },
        { snack: "Fruit salad", description: "Mix together a variety of fresh fruits like apples, bananas, and oranges." },
        { snack: "Hummus with vegetables", description: "Enjoy hummus with sliced bell peppers, cucumbers, and carrots." },
        { snack: "Greek yogurt with honey", description: "Top Greek yogurt with a drizzle of honey and some granola." },
        { snack: "Cheese and crackers", description: "Pair your favorite cheese with whole grain crackers." },
        { snack: "Apple slices with peanut butter", description: "Slice an apple and enjoy with a tablespoon of peanut butter." },
        { snack: "Smoothie with spinach", description: "Blend together spinach, banana, and almond milk for a refreshing smoothie." },
        { snack: "Cottage cheese with pineapple", description: "Mix cottage cheese with fresh pineapple chunks." },
        { snack: "Popcorn", description: "Air-pop some popcorn and season lightly with salt." },
        { snack: "Rice cakes with avocado", description: "Spread avocado on rice cakes for a crunchy snack." },
        { snack: "Trail mix", description: "Combine nuts, dried fruits, and a sprinkle of dark chocolate chips." },
        { snack: "Yogurt parfait", description: "Layer yogurt with granola and fresh berries in a glass." },
        { snack: "Vegetable sticks with ranch dip", description: "Slice cucumbers, carrots, and bell peppers to dip in ranch dressing." },
        { snack: "Hard-boiled eggs", description: "Prepare hard-boiled eggs for a protein-packed snack." },
        { snack: "Rice crackers with tuna", description: "Top rice crackers with canned tuna and a squeeze of lemon." },
        { snack: "Cherry tomatoes with mozzarella", description: "Enjoy cherry tomatoes with bite-sized mozzarella cheese." },
        { snack: "Pita chips with hummus", description: "Dip pita chips into your favorite hummus." },
        { snack: "Banana with almond butter", description: "Spread almond butter on a banana for a quick energy boost." },
        { snack: "Edamame", description: "Boil edamame pods and sprinkle with sea salt." },
        { snack: "Cucumber slices with cream cheese", description: "Spread cream cheese on cucumber slices." }
    ],
    diabetic: [
        { snack: "Mixed nuts", description: "A handful of mixed nuts like almonds, walnuts, and cashews." },
        { snack: "Berries with cottage cheese", description: "Pair fresh berries with cottage cheese." },
        { snack: "Carrot sticks with hummus", description: "Enjoy carrot sticks with hummus for a crunchy snack." },
        { snack: "Greek yogurt with almonds", description: "Top Greek yogurt with almonds and a sprinkle of cinnamon." },
        { snack: "Cheese slices with apple", description: "Pair cheese slices with apple slices." },
        { snack: "Sugar-free yogurt", description: "Choose a sugar-free yogurt with low glycemic index fruits." },
        { snack: "Celery sticks with peanut butter", description: "Spread peanut butter on celery sticks." },
        { snack: "Cherry tomatoes with mozzarella", description: "Enjoy cherry tomatoes with bite-sized mozzarella cheese." },
        { snack: "Avocado with cottage cheese", description: "Slice avocado and serve with cottage cheese." },
        { snack: "Hard-boiled eggs", description: "Prepare hard-boiled eggs for a protein-packed snack." },
        { snack: "Almond butter on whole grain crackers", description: "Spread almond butter on whole grain crackers." },
        { snack: "Sugar-free gelatin", description: "Enjoy a serving of sugar-free gelatin." },
        { snack: "Pumpkin seeds", description: "Roast pumpkin seeds for a nutritious snack." },
        { snack: "Cucumber slices with cream cheese", description: "Spread cream cheese on cucumber slices." },
        { snack: "Turkey slices with cucumber", description: "Wrap turkey slices around cucumber sticks." },
        { snack: "Whole grain toast with avocado", description: "Toast whole grain bread and top with avocado slices." },
        { snack: "Edamame", description: "Boil edamame pods and sprinkle with sea salt." },
        { snack: "Sugar-free applesauce", description: "Choose sugar-free applesauce cups." },
        { snack: "Yogurt with chia seeds", description: "Mix yogurt with chia seeds and a drizzle of honey." },
        { snack: "Seaweed snacks", description: "Enjoy roasted seaweed snacks for a savory treat." }
    ]
};

// Export all meal options and snack options
module.exports = {
    breakfastOptions,
    lunchOptions,
    dinnerOptions,
    snackOptions
};
